/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jing_ffmpegplayer_JingPlayer */

#ifndef _Included_com_jing_ffmpegplayer_JingPlayer
#define _Included_com_jing_ffmpegplayer_JingPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jing_ffmpegplayer_JingPlayer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_jing_ffmpegplayer_JingPlayer_render(JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
