/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jing_appupdate_utils_BsPatch */

#ifndef _Included_com_jing_appupdate_utils_BsPatch
#define _Included_com_jing_appupdate_utils_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jing_appupdate_utils_BsPatch
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jing_appupdate_utils_BsPatch_patch
        (JNIEnv *, jclass, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_jing_appupdate_utils_BsDiff_diff
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
