/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxhj_ffmpegwithposix_JingPlayer */

#ifndef _Included_com_dxhj_ffmpegwithposix_JingPlayer
#define _Included_com_dxhj_ffmpegwithposix_JingPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxhj_ffmpegwithposix_JingPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_dxhj_ffmpegwithposix_JingPlayer_render
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_dxhj_ffmpegwithposix_JingPlayer
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dxhj_ffmpegwithposix_JingPlayer_sound
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dxhj_ffmpegwithposix_JingPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_dxhj_ffmpegwithposix_JingPlayer_play
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
